#include "qsort1.h"
#include "qsort1is.h"
#include "qsort2-larger.h"
#include "qsort2-yaro.h"
#include "qsort2-sample.h"
#include "qsort2-count.h"
#include "qsort2branchfree.h"
#include "qsort3.h"
#include "qsort3opt.h"
#include "qsort3sample.h"

//#include "qsort-copy-store-classification.h"
#include "qsort1lomuto.h"
//#include "qsort1lomuto.h"
