    // Automatically generated by invoking
    // ruby gen_k_pivot_algorithm.rb with parameters
    //  15 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
    #include <algorithm>

    namespace qsort150000000000000000{

    template <typename Iterator>
    void sort(Iterator left, Iterator right)
    {
        typedef typename std::iterator_traits<Iterator>::value_type value_type;
        if (right - left < 500)
        {
            qsort3::three_pivot(left, right);
        }
        else
        {
        networks::sort15(*(left +  0), *(left +  1), *(left +  2), *(left +  3), *(left +  4), *(left +  5), *(left +  6), *(left +  7), *(right - 6), *(right - 5), *(right - 4), *(right - 3), *(right - 2), *(right - 1), *(right - 0));

        value_type p1 = *(left + 0);
        value_type p2 = *(left + 1);
        value_type p3 = *(left + 2);
        value_type p4 = *(left + 3);
        value_type p5 = *(left + 4);
        value_type p6 = *(left + 5);
        value_type p7 = *(left + 6);
        value_type p8 = *(left + 7);
        value_type p9 = *(right - 6);
        value_type p10 = *(right - 5);
        value_type p11 = *(right - 4);
        value_type p12 = *(right - 3);
        value_type p13 = *(right - 2);
        value_type p14 = *(right - 1);
        value_type p15 = *(right - 0);

        Iterator g1 = left + 8;
        Iterator g2 = left + 8;
        Iterator g3 = left + 8;
        Iterator g4 = left + 8;
        Iterator g5 = left + 8;
        Iterator g6 = left + 8;
        Iterator g7 = left + 8;
        Iterator g14 = right - 7;
        Iterator g13 = right - 7;
        Iterator g12 = right - 7;
        Iterator g11 = right - 7;
        Iterator g10 = right - 7;
        Iterator g9 = right - 7;
        Iterator g8 = right - 7;

        Iterator i = left + 8;
        Iterator j = right - 7;

        while (i <= j)
        {
            while (*i < p8)
            {
                if (*i > p7)
                {
                    i++; 
                }
                else
                {
                    if (*i > p6)
                    {
                        rotations::rotate2(*i, *g7);
                        i++; g7++; 
                    }
                    else
                    {
                        if (*i > p5)
                        {
                            rotations::rotate3(*i, *g7, *g6);
                            i++; g7++; g6++; 
                        }
                        else
                        {
                            if (*i > p4)
                            {
                                rotations::rotate4(*i, *g7, *g6, *g5);
                                i++; g7++; g6++; g5++; 
                            }
                            else
                            {
                                if (*i > p3)
                                {
                                    rotations::rotate5(*i, *g7, *g6, *g5, *g4);
                                    i++; g7++; g6++; g5++; g4++; 
                                }
                                else
                                {
                                    if (*i > p2)
                                    {
                                        rotations::rotate6(*i, *g7, *g6, *g5, *g4, *g3);
                                        i++; g7++; g6++; g5++; g4++; g3++; 
                                    }
                                    else
                                    {
                                        if (*i > p1)
                                        {
                                            rotations::rotate7(*i, *g7, *g6, *g5, *g4, *g3, *g2);
                                            i++; g7++; g6++; g5++; g4++; g3++; g2++; 
                                        }
                                        else
                                        {
                                                rotations::rotate8(*i, *g7, *g6, *g5, *g4, *g3, *g2, *g1);
                                                i++; g7++; g6++; g5++; g4++; g3++; g2++; g1++; 
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            while (*j > p8)
            {
                if (*j < p9)
                {
                    j--; 
                }
                else
                {
                    if (*j < p10)
                    {
                        rotations::rotate2(*j, *g8);
                        j--; g8--; 
                    }
                    else
                    {
                        if (*j < p11)
                        {
                            rotations::rotate3(*j, *g8, *g9);
                            j--; g8--; g9--; 
                        }
                        else
                        {
                            if (*j < p12)
                            {
                                rotations::rotate4(*j, *g8, *g9, *g10);
                                j--; g8--; g9--; g10--; 
                            }
                            else
                            {
                                if (*j < p13)
                                {
                                    rotations::rotate5(*j, *g8, *g9, *g10, *g11);
                                    j--; g8--; g9--; g10--; g11--; 
                                }
                                else
                                {
                                    if (*j < p14)
                                    {
                                        rotations::rotate6(*j, *g8, *g9, *g10, *g11, *g12);
                                        j--; g8--; g9--; g10--; g11--; g12--; 
                                    }
                                    else
                                    {
                                        if (*j < p15)
                                        {
                                            rotations::rotate7(*j, *g8, *g9, *g10, *g11, *g12, *g13);
                                            j--; g8--; g9--; g10--; g11--; g12--; g13--; 
                                        }
                                        else
                                        {
                                                rotations::rotate8(*j, *g8, *g9, *g10, *g11, *g12, *g13, *g14);
                                                j--; g8--; g9--; g10--; g11--; g12--; g13--; g14--; 
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            if (i <= j)
            {
                if (*i < p9)
                {
                    if (*j > p7)
                    {
                        // rotate a8 and a7 elements
                        rotations::rotate2(*i, *j);
                        i++, j--;
                    }
                    else
                    {
                        if (*j > p6)
                        {
                            // rotate a8 and a6 elements
                            rotations::rotate3(*i, *g7, *j);
                            i++, j--, g7++;
                        }
                        else
                        {
                            if (*j > p5)
                            {
                                // rotate a8 and a5 elements
                                rotations::rotate4(*i, *g7, *g6, *j);
                                i++, j--, g7++, g6++;
                            }
                            else
                            {
                                if (*j > p4)
                                {
                                    // rotate a8 and a4 elements
                                    rotations::rotate5(*i, *g7, *g6, *g5, *j);
                                    i++, j--, g7++, g6++, g5++;
                                }
                                else
                                {
                                    if (*j > p3)
                                    {
                                        // rotate a8 and a3 elements
                                        rotations::rotate6(*i, *g7, *g6, *g5, *g4, *j);
                                        i++, j--, g7++, g6++, g5++, g4++;
                                    }
                                    else
                                    {
                                        if (*j > p2)
                                        {
                                            // rotate a8 and a2 elements
                                            rotations::rotate7(*i, *g7, *g6, *g5, *g4, *g3, *j);
                                            i++, j--, g7++, g6++, g5++, g4++, g3++;
                                        }
                                        else
                                        {
                                            if (*j > p1)
                                            {
                                                // rotate a8 and a1 elements
                                                rotations::rotate8(*i, *g7, *g6, *g5, *g4, *g3, *g2, *j);
                                                i++, j--, g7++, g6++, g5++, g4++, g3++, g2++;
                                            }
                                            else
                                            {
                                                // rotate a8 and a0 elements
                                                rotations::rotate9(*i, *g7, *g6, *g5, *g4, *g3, *g2, *g1, *j);
                                                i++, j--, g7++, g6++, g5++, g4++, g3++, g2++, g1++;
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
                else
                {
                    if (*i < p10)
                    {
                        if (*j > p7)
                        {
                            // rotate a9 and a7 elements
                            rotations::rotate3(*i, *j, *g8);
                            i++, j--, g8--;
                        }
                        else
                        {
                            if (*j > p6)
                            {
                                // rotate a9 and a6 elements
                                rotations::rotate4(*i, *g7, *j, *g8);
                                i++, j--, g7++, g8--;
                            }
                            else
                            {
                                if (*j > p5)
                                {
                                    // rotate a9 and a5 elements
                                    rotations::rotate5(*i, *g7, *g6, *j, *g8);
                                    i++, j--, g7++, g6++, g8--;
                                }
                                else
                                {
                                    if (*j > p4)
                                    {
                                        // rotate a9 and a4 elements
                                        rotations::rotate6(*i, *g7, *g6, *g5, *j, *g8);
                                        i++, j--, g7++, g6++, g5++, g8--;
                                    }
                                    else
                                    {
                                        if (*j > p3)
                                        {
                                            // rotate a9 and a3 elements
                                            rotations::rotate7(*i, *g7, *g6, *g5, *g4, *j, *g8);
                                            i++, j--, g7++, g6++, g5++, g4++, g8--;
                                        }
                                        else
                                        {
                                            if (*j > p2)
                                            {
                                                // rotate a9 and a2 elements
                                                rotations::rotate8(*i, *g7, *g6, *g5, *g4, *g3, *j, *g8);
                                                i++, j--, g7++, g6++, g5++, g4++, g3++, g8--;
                                            }
                                            else
                                            {
                                                if (*j > p1)
                                                {
                                                    // rotate a9 and a1 elements
                                                    rotations::rotate9(*i, *g7, *g6, *g5, *g4, *g3, *g2, *j, *g8);
                                                    i++, j--, g7++, g6++, g5++, g4++, g3++, g2++, g8--;
                                                }
                                                else
                                                {
                                                    // rotate a9 and a0 elements
                                                    rotations::rotate10(*i, *g7, *g6, *g5, *g4, *g3, *g2, *g1, *j, *g8);
                                                    i++, j--, g7++, g6++, g5++, g4++, g3++, g2++, g1++, g8--;
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                    else
                    {
                        if (*i < p11)
                        {
                            if (*j > p7)
                            {
                                // rotate a10 and a7 elements
                                rotations::rotate4(*i, *j, *g8, *g9);
                                i++, j--, g8--, g9--;
                            }
                            else
                            {
                                if (*j > p6)
                                {
                                    // rotate a10 and a6 elements
                                    rotations::rotate5(*i, *g7, *j, *g8, *g9);
                                    i++, j--, g7++, g8--, g9--;
                                }
                                else
                                {
                                    if (*j > p5)
                                    {
                                        // rotate a10 and a5 elements
                                        rotations::rotate6(*i, *g7, *g6, *j, *g8, *g9);
                                        i++, j--, g7++, g6++, g8--, g9--;
                                    }
                                    else
                                    {
                                        if (*j > p4)
                                        {
                                            // rotate a10 and a4 elements
                                            rotations::rotate7(*i, *g7, *g6, *g5, *j, *g8, *g9);
                                            i++, j--, g7++, g6++, g5++, g8--, g9--;
                                        }
                                        else
                                        {
                                            if (*j > p3)
                                            {
                                                // rotate a10 and a3 elements
                                                rotations::rotate8(*i, *g7, *g6, *g5, *g4, *j, *g8, *g9);
                                                i++, j--, g7++, g6++, g5++, g4++, g8--, g9--;
                                            }
                                            else
                                            {
                                                if (*j > p2)
                                                {
                                                    // rotate a10 and a2 elements
                                                    rotations::rotate9(*i, *g7, *g6, *g5, *g4, *g3, *j, *g8, *g9);
                                                    i++, j--, g7++, g6++, g5++, g4++, g3++, g8--, g9--;
                                                }
                                                else
                                                {
                                                    if (*j > p1)
                                                    {
                                                        // rotate a10 and a1 elements
                                                        rotations::rotate10(*i, *g7, *g6, *g5, *g4, *g3, *g2, *j, *g8, *g9);
                                                        i++, j--, g7++, g6++, g5++, g4++, g3++, g2++, g8--, g9--;
                                                    }
                                                    else
                                                    {
                                                        // rotate a10 and a0 elements
                                                        rotations::rotate11(*i, *g7, *g6, *g5, *g4, *g3, *g2, *g1, *j, *g8, *g9);
                                                        i++, j--, g7++, g6++, g5++, g4++, g3++, g2++, g1++, g8--, g9--;
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                        else
                        {
                            if (*i < p12)
                            {
                                if (*j > p7)
                                {
                                    // rotate a11 and a7 elements
                                    rotations::rotate5(*i, *j, *g8, *g9, *g10);
                                    i++, j--, g8--, g9--, g10--;
                                }
                                else
                                {
                                    if (*j > p6)
                                    {
                                        // rotate a11 and a6 elements
                                        rotations::rotate6(*i, *g7, *j, *g8, *g9, *g10);
                                        i++, j--, g7++, g8--, g9--, g10--;
                                    }
                                    else
                                    {
                                        if (*j > p5)
                                        {
                                            // rotate a11 and a5 elements
                                            rotations::rotate7(*i, *g7, *g6, *j, *g8, *g9, *g10);
                                            i++, j--, g7++, g6++, g8--, g9--, g10--;
                                        }
                                        else
                                        {
                                            if (*j > p4)
                                            {
                                                // rotate a11 and a4 elements
                                                rotations::rotate8(*i, *g7, *g6, *g5, *j, *g8, *g9, *g10);
                                                i++, j--, g7++, g6++, g5++, g8--, g9--, g10--;
                                            }
                                            else
                                            {
                                                if (*j > p3)
                                                {
                                                    // rotate a11 and a3 elements
                                                    rotations::rotate9(*i, *g7, *g6, *g5, *g4, *j, *g8, *g9, *g10);
                                                    i++, j--, g7++, g6++, g5++, g4++, g8--, g9--, g10--;
                                                }
                                                else
                                                {
                                                    if (*j > p2)
                                                    {
                                                        // rotate a11 and a2 elements
                                                        rotations::rotate10(*i, *g7, *g6, *g5, *g4, *g3, *j, *g8, *g9, *g10);
                                                        i++, j--, g7++, g6++, g5++, g4++, g3++, g8--, g9--, g10--;
                                                    }
                                                    else
                                                    {
                                                        if (*j > p1)
                                                        {
                                                            // rotate a11 and a1 elements
                                                            rotations::rotate11(*i, *g7, *g6, *g5, *g4, *g3, *g2, *j, *g8, *g9, *g10);
                                                            i++, j--, g7++, g6++, g5++, g4++, g3++, g2++, g8--, g9--, g10--;
                                                        }
                                                        else
                                                        {
                                                            // rotate a11 and a0 elements
                                                            rotations::rotate12(*i, *g7, *g6, *g5, *g4, *g3, *g2, *g1, *j, *g8, *g9, *g10);
                                                            i++, j--, g7++, g6++, g5++, g4++, g3++, g2++, g1++, g8--, g9--, g10--;
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                            else
                            {
                                if (*i < p13)
                                {
                                    if (*j > p7)
                                    {
                                        // rotate a12 and a7 elements
                                        rotations::rotate6(*i, *j, *g8, *g9, *g10, *g11);
                                        i++, j--, g8--, g9--, g10--, g11--;
                                    }
                                    else
                                    {
                                        if (*j > p6)
                                        {
                                            // rotate a12 and a6 elements
                                            rotations::rotate7(*i, *g7, *j, *g8, *g9, *g10, *g11);
                                            i++, j--, g7++, g8--, g9--, g10--, g11--;
                                        }
                                        else
                                        {
                                            if (*j > p5)
                                            {
                                                // rotate a12 and a5 elements
                                                rotations::rotate8(*i, *g7, *g6, *j, *g8, *g9, *g10, *g11);
                                                i++, j--, g7++, g6++, g8--, g9--, g10--, g11--;
                                            }
                                            else
                                            {
                                                if (*j > p4)
                                                {
                                                    // rotate a12 and a4 elements
                                                    rotations::rotate9(*i, *g7, *g6, *g5, *j, *g8, *g9, *g10, *g11);
                                                    i++, j--, g7++, g6++, g5++, g8--, g9--, g10--, g11--;
                                                }
                                                else
                                                {
                                                    if (*j > p3)
                                                    {
                                                        // rotate a12 and a3 elements
                                                        rotations::rotate10(*i, *g7, *g6, *g5, *g4, *j, *g8, *g9, *g10, *g11);
                                                        i++, j--, g7++, g6++, g5++, g4++, g8--, g9--, g10--, g11--;
                                                    }
                                                    else
                                                    {
                                                        if (*j > p2)
                                                        {
                                                            // rotate a12 and a2 elements
                                                            rotations::rotate11(*i, *g7, *g6, *g5, *g4, *g3, *j, *g8, *g9, *g10, *g11);
                                                            i++, j--, g7++, g6++, g5++, g4++, g3++, g8--, g9--, g10--, g11--;
                                                        }
                                                        else
                                                        {
                                                            if (*j > p1)
                                                            {
                                                                // rotate a12 and a1 elements
                                                                rotations::rotate12(*i, *g7, *g6, *g5, *g4, *g3, *g2, *j, *g8, *g9, *g10, *g11);
                                                                i++, j--, g7++, g6++, g5++, g4++, g3++, g2++, g8--, g9--, g10--, g11--;
                                                            }
                                                            else
                                                            {
                                                                // rotate a12 and a0 elements
                                                                rotations::rotate13(*i, *g7, *g6, *g5, *g4, *g3, *g2, *g1, *j, *g8, *g9, *g10, *g11);
                                                                i++, j--, g7++, g6++, g5++, g4++, g3++, g2++, g1++, g8--, g9--, g10--, g11--;
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                                else
                                {
                                    if (*i < p14)
                                    {
                                        if (*j > p7)
                                        {
                                            // rotate a13 and a7 elements
                                            rotations::rotate7(*i, *j, *g8, *g9, *g10, *g11, *g12);
                                            i++, j--, g8--, g9--, g10--, g11--, g12--;
                                        }
                                        else
                                        {
                                            if (*j > p6)
                                            {
                                                // rotate a13 and a6 elements
                                                rotations::rotate8(*i, *g7, *j, *g8, *g9, *g10, *g11, *g12);
                                                i++, j--, g7++, g8--, g9--, g10--, g11--, g12--;
                                            }
                                            else
                                            {
                                                if (*j > p5)
                                                {
                                                    // rotate a13 and a5 elements
                                                    rotations::rotate9(*i, *g7, *g6, *j, *g8, *g9, *g10, *g11, *g12);
                                                    i++, j--, g7++, g6++, g8--, g9--, g10--, g11--, g12--;
                                                }
                                                else
                                                {
                                                    if (*j > p4)
                                                    {
                                                        // rotate a13 and a4 elements
                                                        rotations::rotate10(*i, *g7, *g6, *g5, *j, *g8, *g9, *g10, *g11, *g12);
                                                        i++, j--, g7++, g6++, g5++, g8--, g9--, g10--, g11--, g12--;
                                                    }
                                                    else
                                                    {
                                                        if (*j > p3)
                                                        {
                                                            // rotate a13 and a3 elements
                                                            rotations::rotate11(*i, *g7, *g6, *g5, *g4, *j, *g8, *g9, *g10, *g11, *g12);
                                                            i++, j--, g7++, g6++, g5++, g4++, g8--, g9--, g10--, g11--, g12--;
                                                        }
                                                        else
                                                        {
                                                            if (*j > p2)
                                                            {
                                                                // rotate a13 and a2 elements
                                                                rotations::rotate12(*i, *g7, *g6, *g5, *g4, *g3, *j, *g8, *g9, *g10, *g11, *g12);
                                                                i++, j--, g7++, g6++, g5++, g4++, g3++, g8--, g9--, g10--, g11--, g12--;
                                                            }
                                                            else
                                                            {
                                                                if (*j > p1)
                                                                {
                                                                    // rotate a13 and a1 elements
                                                                    rotations::rotate13(*i, *g7, *g6, *g5, *g4, *g3, *g2, *j, *g8, *g9, *g10, *g11, *g12);
                                                                    i++, j--, g7++, g6++, g5++, g4++, g3++, g2++, g8--, g9--, g10--, g11--, g12--;
                                                                }
                                                                else
                                                                {
                                                                    // rotate a13 and a0 elements
                                                                    rotations::rotate14(*i, *g7, *g6, *g5, *g4, *g3, *g2, *g1, *j, *g8, *g9, *g10, *g11, *g12);
                                                                    i++, j--, g7++, g6++, g5++, g4++, g3++, g2++, g1++, g8--, g9--, g10--, g11--, g12--;
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                    else
                                    {
                                        if (*i < p15)
                                        {
                                            if (*j > p7)
                                            {
                                                // rotate a14 and a7 elements
                                                rotations::rotate8(*i, *j, *g8, *g9, *g10, *g11, *g12, *g13);
                                                i++, j--, g8--, g9--, g10--, g11--, g12--, g13--;
                                            }
                                            else
                                            {
                                                if (*j > p6)
                                                {
                                                    // rotate a14 and a6 elements
                                                    rotations::rotate9(*i, *g7, *j, *g8, *g9, *g10, *g11, *g12, *g13);
                                                    i++, j--, g7++, g8--, g9--, g10--, g11--, g12--, g13--;
                                                }
                                                else
                                                {
                                                    if (*j > p5)
                                                    {
                                                        // rotate a14 and a5 elements
                                                        rotations::rotate10(*i, *g7, *g6, *j, *g8, *g9, *g10, *g11, *g12, *g13);
                                                        i++, j--, g7++, g6++, g8--, g9--, g10--, g11--, g12--, g13--;
                                                    }
                                                    else
                                                    {
                                                        if (*j > p4)
                                                        {
                                                            // rotate a14 and a4 elements
                                                            rotations::rotate11(*i, *g7, *g6, *g5, *j, *g8, *g9, *g10, *g11, *g12, *g13);
                                                            i++, j--, g7++, g6++, g5++, g8--, g9--, g10--, g11--, g12--, g13--;
                                                        }
                                                        else
                                                        {
                                                            if (*j > p3)
                                                            {
                                                                // rotate a14 and a3 elements
                                                                rotations::rotate12(*i, *g7, *g6, *g5, *g4, *j, *g8, *g9, *g10, *g11, *g12, *g13);
                                                                i++, j--, g7++, g6++, g5++, g4++, g8--, g9--, g10--, g11--, g12--, g13--;
                                                            }
                                                            else
                                                            {
                                                                if (*j > p2)
                                                                {
                                                                    // rotate a14 and a2 elements
                                                                    rotations::rotate13(*i, *g7, *g6, *g5, *g4, *g3, *j, *g8, *g9, *g10, *g11, *g12, *g13);
                                                                    i++, j--, g7++, g6++, g5++, g4++, g3++, g8--, g9--, g10--, g11--, g12--, g13--;
                                                                }
                                                                else
                                                                {
                                                                    if (*j > p1)
                                                                    {
                                                                        // rotate a14 and a1 elements
                                                                        rotations::rotate14(*i, *g7, *g6, *g5, *g4, *g3, *g2, *j, *g8, *g9, *g10, *g11, *g12, *g13);
                                                                        i++, j--, g7++, g6++, g5++, g4++, g3++, g2++, g8--, g9--, g10--, g11--, g12--, g13--;
                                                                    }
                                                                    else
                                                                    {
                                                                        // rotate a14 and a0 elements
                                                                        rotations::rotate15(*i, *g7, *g6, *g5, *g4, *g3, *g2, *g1, *j, *g8, *g9, *g10, *g11, *g12, *g13);
                                                                        i++, j--, g7++, g6++, g5++, g4++, g3++, g2++, g1++, g8--, g9--, g10--, g11--, g12--, g13--;
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                        else
                                        {
                                            if (*j > p7)
                                            {
                                                // rotate a15 and a7 elements
                                                rotations::rotate9(*i, *j, *g8, *g9, *g10, *g11, *g12, *g13, *g14);
                                                i++, j--, g8--, g9--, g10--, g11--, g12--, g13--, g14--;
                                            }
                                            else
                                            {
                                                if (*j > p6)
                                                {
                                                    // rotate a15 and a6 elements
                                                    rotations::rotate10(*i, *g7, *j, *g8, *g9, *g10, *g11, *g12, *g13, *g14);
                                                    i++, j--, g7++, g8--, g9--, g10--, g11--, g12--, g13--, g14--;
                                                }
                                                else
                                                {
                                                    if (*j > p5)
                                                    {
                                                        // rotate a15 and a5 elements
                                                        rotations::rotate11(*i, *g7, *g6, *j, *g8, *g9, *g10, *g11, *g12, *g13, *g14);
                                                        i++, j--, g7++, g6++, g8--, g9--, g10--, g11--, g12--, g13--, g14--;
                                                    }
                                                    else
                                                    {
                                                        if (*j > p4)
                                                        {
                                                            // rotate a15 and a4 elements
                                                            rotations::rotate12(*i, *g7, *g6, *g5, *j, *g8, *g9, *g10, *g11, *g12, *g13, *g14);
                                                            i++, j--, g7++, g6++, g5++, g8--, g9--, g10--, g11--, g12--, g13--, g14--;
                                                        }
                                                        else
                                                        {
                                                            if (*j > p3)
                                                            {
                                                                // rotate a15 and a3 elements
                                                                rotations::rotate13(*i, *g7, *g6, *g5, *g4, *j, *g8, *g9, *g10, *g11, *g12, *g13, *g14);
                                                                i++, j--, g7++, g6++, g5++, g4++, g8--, g9--, g10--, g11--, g12--, g13--, g14--;
                                                            }
                                                            else
                                                            {
                                                                if (*j > p2)
                                                                {
                                                                    // rotate a15 and a2 elements
                                                                    rotations::rotate14(*i, *g7, *g6, *g5, *g4, *g3, *j, *g8, *g9, *g10, *g11, *g12, *g13, *g14);
                                                                    i++, j--, g7++, g6++, g5++, g4++, g3++, g8--, g9--, g10--, g11--, g12--, g13--, g14--;
                                                                }
                                                                else
                                                                {
                                                                    if (*j > p1)
                                                                    {
                                                                        // rotate a15 and a1 elements
                                                                        rotations::rotate15(*i, *g7, *g6, *g5, *g4, *g3, *g2, *j, *g8, *g9, *g10, *g11, *g12, *g13, *g14);
                                                                        i++, j--, g7++, g6++, g5++, g4++, g3++, g2++, g8--, g9--, g10--, g11--, g12--, g13--, g14--;
                                                                    }
                                                                    else
                                                                    {
                                                                        // rotate a15 and a0 elements
                                                                        rotations::rotate16(*i, *g7, *g6, *g5, *g4, *g3, *g2, *g1, *j, *g8, *g9, *g10, *g11, *g12, *g13, *g14);
                                                                        i++, j--, g7++, g6++, g5++, g4++, g3++, g2++, g1++, g8--, g9--, g10--, g11--, g12--, g13--, g14--;
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        rotations::rotate9(*(left + 7), *(g1 - 1), *(g2 - 1), *(g3 - 1), *(g4 - 1), *(g5 - 1), *(g6 - 1), *(g7 - 1), *(i - 1));
        rotations::rotate8(*(left + 6), *(g1 - 2), *(g2 - 2), *(g3 - 2), *(g4 - 2), *(g5 - 2), *(g6 - 2), *(g7 - 2));
        rotations::rotate7(*(left + 5), *(g1 - 3), *(g2 - 3), *(g3 - 3), *(g4 - 3), *(g5 - 3), *(g6 - 3));
        rotations::rotate6(*(left + 4), *(g1 - 4), *(g2 - 4), *(g3 - 4), *(g4 - 4), *(g5 - 4));
        rotations::rotate5(*(left + 3), *(g1 - 5), *(g2 - 5), *(g3 - 5), *(g4 - 5));
        rotations::rotate4(*(left + 2), *(g1 - 6), *(g2 - 6), *(g3 - 6));
        rotations::rotate3(*(left + 1), *(g1 - 7), *(g2 - 7));
        rotations::rotate2(*(left + 0), *(g1 - 8));

        rotations::rotate8(*(right - 6), *(g14 + 1), *(g13 + 1), *(g12 + 1), *(g11 + 1), *(g10 + 1), *(g9 + 1), *(g8 + 1));
        rotations::rotate7(*(right - 5), *(g14 + 2), *(g13 + 2), *(g12 + 2), *(g11 + 2), *(g10 + 2), *(g9 + 2));
        rotations::rotate6(*(right - 4), *(g14 + 3), *(g13 + 3), *(g12 + 3), *(g11 + 3), *(g10 + 3));
        rotations::rotate5(*(right - 3), *(g14 + 4), *(g13 + 4), *(g12 + 4), *(g11 + 4));
        rotations::rotate4(*(right - 2), *(g14 + 5), *(g13 + 5), *(g12 + 5));
        rotations::rotate3(*(right - 1), *(g14 + 6), *(g13 + 6));
        rotations::rotate2(*(right - 0), *(g14 + 7));

        sort(left, g1 - 9);
        sort(g1 - 7, g2 - 8);
        sort(g2 - 6, g3 - 7);
        sort(g3 - 5, g4 - 6);
        sort(g4 - 4, g5 - 5);
        sort(g5 - 3, g6 - 4);
        sort(g6 - 2, g7 - 3);
        sort(g7 - 1, i - 2);
        sort(i - 0, g8 + 0);
        sort(g8 + 2, g9 + 1);
        sort(g9 + 3, g10 + 2);
        sort(g10 + 4, g11 + 3);
        sort(g11 + 5, g12 + 4);
        sort(g12 + 6, g13 + 5);
        sort(g13 + 7, g14 + 6);
        sort(g14 + 8, right);
    }
}

template <typename ValueType>
void qsort()
{
    assert( g_input_size % sizeof(ValueType) == 0 );

    ValueType* input = (ValueType*)g_input;
    size_t n = g_input_size / sizeof(ValueType);

    sort(input, input + n - 1);
}

CONTESTANT_REGISTER_ALL(qsort, "qsort150000000000000000", "Quicksort, 15 pivots");

} // namespace
