    // Automatically generated by invoking
    // ruby gen_k_pivot_algorithm.rb with parameters
    //  3 0 0 0 0 
    #include <algorithm>

    namespace qsort30000{

    template <typename Iterator>
    void sort(Iterator left, Iterator right)
    {
        typedef typename std::iterator_traits<Iterator>::value_type value_type;
        if (right - left < 500)
        {
            qsort3::three_pivot(left, right);
        }
        else
        {
        networks::sort3(*(left +  0), *(left +  1), *(right - 0));

        value_type p1 = *(left + 0);
        value_type p2 = *(left + 1);
        value_type p3 = *(right - 0);

        Iterator g1 = left + 2;
        Iterator g2 = right - 1;

        Iterator i = left + 2;
        Iterator j = right - 1;

        while (i <= j)
        {
            while (*i < p2)
            {
                if (*i > p1)
                {
                    i++; 
                }
                else
                {
                        rotations::rotate2(*i, *g1);
                        i++; g1++; 
                }
            }
            while (*j > p2)
            {
                if (*j < p3)
                {
                    j--; 
                }
                else
                {
                        rotations::rotate2(*j, *g2);
                        j--; g2--; 
                }
            }
            if (i <= j)
            {
                if (*i < p3)
                {
                    if (*j > p1)
                    {
                        // rotate a2 and a1 elements
                        rotations::rotate2(*i, *j);
                        i++, j--;
                    }
                    else
                    {
                        // rotate a2 and a0 elements
                        rotations::rotate3(*i, *g1, *j);
                        i++, j--, g1++;
                    }
                }
                else
                {
                    if (*j > p1)
                    {
                        // rotate a3 and a1 elements
                        rotations::rotate3(*i, *j, *g2);
                        i++, j--, g2--;
                    }
                    else
                    {
                        // rotate a3 and a0 elements
                        rotations::rotate4(*i, *g1, *j, *g2);
                        i++, j--, g1++, g2--;
                    }
                }
            }
        }
        rotations::rotate3(*(left + 1), *(g1 - 1), *(i - 1));
        rotations::rotate2(*(left + 0), *(g1 - 2));

        rotations::rotate2(*(right - 0), *(g2 + 1));

        sort(left, g1 - 3);
        sort(g1 - 1, i - 2);
        sort(i - 0, g2 + 0);
        sort(g2 + 2, right);
    }
}

template <typename ValueType>
void qsort()
{
    assert( g_input_size % sizeof(ValueType) == 0 );

    ValueType* input = (ValueType*)g_input;
    size_t n = g_input_size / sizeof(ValueType);

    sort(input, input + n - 1);
}

CONTESTANT_REGISTER_ALL(qsort, "qsort30000", "Quicksort, 3 pivots");

} // namespace
