    // Automatically generated by invoking
    // ruby gen_k_pivot_algorithm.rb with parameters
    //  6 0 0 0 0 0 0 0 
    #include <algorithm>

    namespace qsort60000000{

    template <typename Iterator>
    void sort(Iterator left, Iterator right)
    {
        typedef typename std::iterator_traits<Iterator>::value_type value_type;
        if (right - left < 500)
        {
            qsort3::three_pivot(left, right);
        }
        else
        {
        networks::sort6(*(left +  0), *(left +  1), *(left +  2), *(right - 2), *(right - 1), *(right - 0));

        value_type p1 = *(left + 0);
        value_type p2 = *(left + 1);
        value_type p3 = *(left + 2);
        value_type p4 = *(right - 2);
        value_type p5 = *(right - 1);
        value_type p6 = *(right - 0);

        Iterator g1 = left + 3;
        Iterator g2 = left + 3;
        Iterator g3 = left + 3;
        Iterator g5 = right - 3;
        Iterator g4 = right - 3;

        Iterator i = left + 3;
        Iterator j = right - 3;

        while (i <= j)
        {
            while (*i < p4)
            {
                if (*i > p3)
                {
                    i++; 
                }
                else
                {
                    if (*i > p2)
                    {
                        rotations::rotate2(*i, *g3);
                        i++; g3++; 
                    }
                    else
                    {
                        if (*i > p1)
                        {
                            rotations::rotate3(*i, *g3, *g2);
                            i++; g3++; g2++; 
                        }
                        else
                        {
                                rotations::rotate4(*i, *g3, *g2, *g1);
                                i++; g3++; g2++; g1++; 
                        }
                    }
                }
            }
            while (*j > p4)
            {
                if (*j < p5)
                {
                    j--; 
                }
                else
                {
                    if (*j < p6)
                    {
                        rotations::rotate2(*j, *g4);
                        j--; g4--; 
                    }
                    else
                    {
                            rotations::rotate3(*j, *g4, *g5);
                            j--; g4--; g5--; 
                    }
                }
            }
            if (i <= j)
            {
                if (*i < p5)
                {
                    if (*j > p3)
                    {
                        // rotate a4 and a3 elements
                        rotations::rotate2(*i, *j);
                        i++, j--;
                    }
                    else
                    {
                        if (*j > p2)
                        {
                            // rotate a4 and a2 elements
                            rotations::rotate3(*i, *g3, *j);
                            i++, j--, g3++;
                        }
                        else
                        {
                            if (*j > p1)
                            {
                                // rotate a4 and a1 elements
                                rotations::rotate4(*i, *g3, *g2, *j);
                                i++, j--, g3++, g2++;
                            }
                            else
                            {
                                // rotate a4 and a0 elements
                                rotations::rotate5(*i, *g3, *g2, *g1, *j);
                                i++, j--, g3++, g2++, g1++;
                            }
                        }
                    }
                }
                else
                {
                    if (*i < p6)
                    {
                        if (*j > p3)
                        {
                            // rotate a5 and a3 elements
                            rotations::rotate3(*i, *j, *g4);
                            i++, j--, g4--;
                        }
                        else
                        {
                            if (*j > p2)
                            {
                                // rotate a5 and a2 elements
                                rotations::rotate4(*i, *g3, *j, *g4);
                                i++, j--, g3++, g4--;
                            }
                            else
                            {
                                if (*j > p1)
                                {
                                    // rotate a5 and a1 elements
                                    rotations::rotate5(*i, *g3, *g2, *j, *g4);
                                    i++, j--, g3++, g2++, g4--;
                                }
                                else
                                {
                                    // rotate a5 and a0 elements
                                    rotations::rotate6(*i, *g3, *g2, *g1, *j, *g4);
                                    i++, j--, g3++, g2++, g1++, g4--;
                                }
                            }
                        }
                    }
                    else
                    {
                        if (*j > p3)
                        {
                            // rotate a6 and a3 elements
                            rotations::rotate4(*i, *j, *g4, *g5);
                            i++, j--, g4--, g5--;
                        }
                        else
                        {
                            if (*j > p2)
                            {
                                // rotate a6 and a2 elements
                                rotations::rotate5(*i, *g3, *j, *g4, *g5);
                                i++, j--, g3++, g4--, g5--;
                            }
                            else
                            {
                                if (*j > p1)
                                {
                                    // rotate a6 and a1 elements
                                    rotations::rotate6(*i, *g3, *g2, *j, *g4, *g5);
                                    i++, j--, g3++, g2++, g4--, g5--;
                                }
                                else
                                {
                                    // rotate a6 and a0 elements
                                    rotations::rotate7(*i, *g3, *g2, *g1, *j, *g4, *g5);
                                    i++, j--, g3++, g2++, g1++, g4--, g5--;
                                }
                            }
                        }
                    }
                }
            }
        }
        rotations::rotate4(*(left + 2), *(g1 - 1), *(g2 - 1), *(g3 - 1));
        rotations::rotate3(*(left + 1), *(g1 - 2), *(g2 - 2));
        rotations::rotate2(*(left + 0), *(g1 - 3));

        rotations::rotate4(*(right - 2), *(g5 + 1), *(g4 + 1), *(j + 1));
        rotations::rotate3(*(right - 1), *(g5 + 2), *(g4 + 2));
        rotations::rotate2(*(right - 0), *(g5 + 3));

        sort(left, g1 - 4);
        sort(g1 - 2, g2 - 3);
        sort(g2 - 1, g3 - 2);
        sort(g3 - 0, j);
        sort(j + 2, g4 + 1);
        sort(g4 + 3, g5 + 2);
        sort(g5 + 4, right);
    }
}

template <typename ValueType>
void qsort()
{
    assert( g_input_size % sizeof(ValueType) == 0 );

    ValueType* input = (ValueType*)g_input;
    size_t n = g_input_size / sizeof(ValueType);

    sort(input, input + n - 1);
}

CONTESTANT_REGISTER_ALL(qsort, "qsort60000000", "Quicksort, 6 pivots");

} // namespace
