default:
	bash gen_experiments-fastest.sh
	bash gen_experiments-one-pivot-sampling.sh
	bash gen_experiments-two-pivot-sampling.sh
	bash gen_experiments-three-pivot-sampling.sh
	bash gen_experiments-four-pivot-sampling.sh
	bash gen_experiments-five-pivot-sampling.sh
	bash gen_experiments-six-pivot-sampling.sh
	bash gen_experiments-seven-pivot-sampling.sh
	bash gen_experiments-nine-pivot-sampling.sh
